/**
 * Created by coonrod on 2/20/15.
 */
exports.default = {
    routes: {
        all: [{
            path: 'dashboard/addRedisKey',
            action: 'addRedisKey'
        }, {
            path: 'dashboard/addRedisListItem',
            action: 'addRedisListItem'
        }, {
            path: 'dashboard/addRedisSetItem',
            action: 'addRedisSetItem'
        }, {
            path: 'dashboard/calcStatus',
            action: 'calcStatus'
        }, {
            path: 'dashboard/getAllFailedJobs',
            action: 'getAllFailedJobs'
        }, {
            path: 'dashboard/getAllFailedKeys',
            action: 'getAllFailedKeys'
        }, {
            path: 'dashboard/getAllRunningJobs',
            action: 'getAllRunningJobs'
        }, {
            path: 'dashboard/getCPUusage',
            action: 'getCPUusage'
        }, {
            path: 'dashboard/getPlugins',
            action: 'getPlugins'
        }, {
            path: 'dashboard/getRAMusage',
            action: 'getRAMusage'
        }, {
            path: 'dashboard/getRedisKeyValue',
            action: 'getRedisKeyValue'
        }, {
            path: 'dashboard/getRoutes',
            action: 'getRoutes'
        }, {
            path: 'dashboard/getStaticKeys',
            action: 'getStaticKeys'
        }, {
            path: 'dashboard/getTasksStatistics',
            action: 'getTasksStatistics'
        }, {
            path: 'dashboard/userAdd',
            action: 'userAdd'
        }, {
            path: 'dashboard/userEdit',
            action: 'userEdit'
        }, {
            path: 'dashboard/userDelete',
            action: 'userDelete'
        }, {
            path: 'dashboard/currentUser',
            action: 'currentUser'
        }, {
            path: 'dashboard/login',
            action: 'login'
        }, {
            path: 'dashboard/getUsers',
            action: 'getUsers'
        }, {
            path: 'dashboard/logout',
            action: 'logout'
        }, {
            path: 'dashboard/reEnqueueTask',
            action: 'reEnqueueTask'
        }, {
            path: 'dashboard/removeRedisHashItem',
            action: 'removeRedisHashItem'
        }, {
            path: 'dashboard/removeRedisListItem',
            action: 'removeRedisListItem'
        }, {
            path: 'dashboard/removeRedisSetItem',
            action: 'removeRedisSetItem'
        }, {
            path: 'dashboard/removeRedisZSetItem',
            action: 'removeRedisZSetItem'
        }, {
            path: 'dashboard/updateRedisHashItem',
            action: 'updateRedisHashItem'
        }, {
            path: 'dashboard/updateRedisListItem',
            action: 'updateRedisListItem'
        }, {
            path: 'dashboard/updateRedisSetItem',
            action: 'updateRedisSetItem'
        }, {
            path: 'dashboard/updateRedisZSetItem',
            action: 'updateRedisZSetItem'
        }]
    }
};